### ISSUE TITLE
"Edit this page" button links to non-existant GitHub file (404 - page not found)

### ISSUE THREAD

**Issue by CodeShakingSheep** [renovatebot/renovatebot.github.io#307] opened 2023-08-04 15:54 UTC
### What browser are you using?

Other

### Other browser name

Brave (Chromium based)

### Describe the bug

When clicking the "edit this page" button in the upper right corner of the `platform` sub pages they redirect to non-existant GitHub files. This applies for the following sub pages.

- [Azure DevOps and Azure DevOps Server](https://docs.renovatebot.com/modules/platform/azure/) links to [File not found](https://github.com/renovatebot/renovate/edit/main/docs/usage/modules/platform/azure/index.md)
- [Bitbucket Cloud](https://docs.renovatebot.com/modules/platform/bitbucket/) links to [File not found](https://github.com/renovatebot/renovate/edit/main/docs/usage/modules/platform/bitbucket/index.md)
- [Bitbucket Server](https://docs.renovatebot.com/modules/platform/bitbucket-server/) links to [File not found](https://github.com/renovatebot/renovate/edit/main/docs/usage/modules/platform/bitbucket-server/index.md)

It also applies to those sub pages:
- AWS CodeCommit
- Gitea and Foregjo
- GitHub and GitHub Enterprise Server
- GitLab
- Local

So, it seems to apply to all sub pages of `platform` except `Introduction`.

I just checked some random other pages and also some of them have the same behavior, such as
- [Artifcatory Datasource](https://docs.renovatebot.com/modules/datasource/artifactory/)
- [Aws Machine Image Datasource](https://docs.renovatebot.com/modules/datasource/aws-machine-image/)
- and more

So, it seems to be a more general issue.

### Steps to reproduce

Just click on the pencil icon "Edit this page" in the upper right corner of one of the linked pages.

**Comment by HonkingGoose** [comment] 2023-08-04 17:03
Thank you for the detailed report! Related issue:

- https://github.com/renovatebot/renovate/issues/19309

**Comment by viceice** [comment] 2023-08-05 19:08
Duplicate of #19309

**Closed by viceice** 2023-08-05 19:08 UTC
Labels: bug
