### ISSUE TITLE
Abbreviation tooltips don't work anymore

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#287] opened 2023-05-18 11:03 UTC
### What browser are you using?

Firefox

### Describe the bug

No tooltips when hovering over an abbreviation listed in the [`abbreviations.md` file](https://github.com/renovatebot/renovatebot.github.io/blob/main/includes/abbreviations.md) on the production site. This feature worked a while back.

### Steps to reproduce

1. Go to https://docs.renovatebot.com/getting-started/running/#npm-package-cli
2. Hover over the `CLI` abbreviation with your mouse/pointer device
3. No tooltip on hover

### Additional context

The official/upstream Material for MkDocs site has working tooltips.

**Comment by HonkingGoose** [comment] 2023-05-18 11:55
According to `git bisect` the problem is with the commit that updated us to `mkdocs-material to v9.1.12`.

Here's the `git bisect log` output:

```shell
# git bisect log
git bisect start
# status: waiting for both good and bad commits
# bad: [c95f937c95d118e7b6de801fd297b672f2871923] chore(docs): update deps/renovate digest to b5d74a8
git bisect bad c95f937c95d118e7b6de801fd297b672f2871923
# status: waiting for good commit(s), bad commit known
# good: [6978ff0bf3a49df62b583185f164994819bbe2d3] chore: show tooltip when hovering over abbreviation (#207)
git bisect good 6978ff0bf3a49df62b583185f164994819bbe2d3
# good: [9c7f84cca1d807ad4a2e4e7cbdc286a0e6d8515c] chore(docs): update deps/renovate digest to 6beeba6
git bisect good 9c7f84cca1d807ad4a2e4e7cbdc286a0e6d8515c
# good: [41d74eb7d98be911a99726fcadefbcef20559e4e] chore(docs): update deps/renovate digest to 56c161a
git bisect good 41d74eb7d98be911a99726fcadefbcef20559e4e
# good: [aea7a13eba8a2f7111167c5c66c717515f624901] chore(docs): update deps/renovate digest to c5a5c89
git bisect good aea7a13eba8a2f7111167c5c66c717515f624901
# good: [cae583a258f4226ea64d1deb52a590eab608fcec] chore(docs): update deps/renovate digest to b27ec63
git bisect good cae583a258f4226ea64d1deb52a590eab608fcec
# good: [522c36d212b02cfe1559d97823fc2d37632adad0] chore(docs): update deps/renovate digest to 1cd405b
git bisect good 522c36d212b02cfe1559d97823fc2d37632adad0
# good: [fa7e2c22f72940f69a57beac0f853c846407cbe8] chore(deps): update dependency mkdocs-material to v9.1.11
git bisect good fa7e2c22f72940f69a57beac0f853c846407cbe8
# good: [e63cec6587edd1f7b4605cb47e387a1dcdd91bfe] chore(docs): update deps/renovate digest to e74e480
git bisect good e63cec6587edd1f7b4605cb47e387a1dcdd91bfe
# bad: [b812b9c7acfe63da462c3242e4d248b16972a75b] chore(docs): update deps/renovate digest to f2977e4
git bisect bad b812b9c7acfe63da462c3242e4d248b16972a75b
# bad: [411f115201ef401673050a6815db929f3f0854bd] chore(deps): update dependency mkdocs-material to v9.1.12
git bisect bad 411f115201ef401673050a6815db929f3f0854bd
# good: [6c64ab9a36d4856e48837bf0779eaadfaeca8cbc] chore(docs): update deps/renovate digest to 85fbad1
git bisect good 6c64ab9a36d4856e48837bf0779eaadfaeca8cbc
# first bad commit: [411f115201ef401673050a6815db929f3f0854bd] chore(deps): update dependency mkdocs-material to v9.1.12
```

The weird thing is that abbreviations are working on the official Material for MkDocs site, but broken on ours. 😕 We should first try updating to the latest version of Material for MkDocs, and see if that fixes the problem.

**Comment by viceice** [comment] 2023-05-19 09:52
update merged

**Comment by HonkingGoose** [comment] 2023-05-19 10:38
The abbreviations are working on `v9.1.13` again. 🥳

**Closed** 2023-05-19 10:39 UTC
Labels: bug

**Comment by HonkingGoose** [comment] 2023-05-19 11:55
I created a discussion to tell the upstream maintainers about the possible regression:

- https://github.com/squidfunk/mkdocs-material/discussions/5529

**Comment by viceice** [comment] 2023-05-19 18:15
thanks for evaluation of the root cause
