### ISSUE TITLE
Some documentation searches are giving misleading results

### ISSUE THREAD

**Issue by TWiStErRob** [renovatebot/renovatebot.github.io#164] opened 2022-04-11 22:04 UTC
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

For example if you search for "depTypes":
![image](https://user-images.githubusercontent.com/2906988/162840754-3d82862f-4e6b-48e7-82dd-1756d36361dc.png)

the results show "File Matching" as the header, even though the results are pointing to specific manager documentations:
 * https://docs.renovatebot.com/modules/manager/pipenv/
 * https://docs.renovatebot.com/modules/manager/poetry/
 * https://docs.renovatebot.com/modules/manager/npm/

I would expect "Automated Dependency Updates for Pipenv" to show instead for the first result for example.

### Relevant debug logs

N/A

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by HonkingGoose** [comment] 2022-04-12 19:57
The individual manager pages are absent from the `nav` in `mkdocs.yml`. Maybe this causes weirdness when a search hits one of those pages?

https://github.com/renovatebot/renovatebot.github.io/blob/2453ba6333761cb6a8f783a6d9b32040f34e0835/mkdocs.yml#L114-L174

Issue #149 tracks the missing items in the `nav`.

---

Here are the [docs for search in Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/). I don't think there's much we can do ourselves to improve the search.

**Comment by HonkingGoose** [comment] 2023-01-05 12:21
> For some reason it's using the first heading as the title for the page

This seems to be fixed after we updated to Material for MkDocs 9 (or because of other changes). Here's a new screenshot for the `depTypes` search:

![deptypes-search-material-mkdocs-nine](https://user-images.githubusercontent.com/34918129/210777752-b7c94110-c2e9-4d17-9433-e930b1f7e934.png)

Overall the new search looks better, and shows more context for results.

## Can't find presets via their name

I can't find the presets via the Material for MkDocs search. Steps to reproduce:

1. Go to production docs site.
1. Enter `workarounds:javaLTSVersions` in the search bar
1. Search bar says: "no matching documents"
1. But we do have a page with `workarounds:javaLTSVersions` as the heading title: https://docs.renovatebot.com/presets-workarounds/#workaroundsjavaltsversions

**Comment by viceice** [comment] 2023-01-05 13:32
![image](https://user-images.githubusercontent.com/1798109/210791527-07683eeb-fe02-466a-bbf4-8fc9697ffe0b.png)

I'm closing this, as new mkdocs material is much better

**Closed by viceice** 2023-01-05 13:32 UTC
Labels: bug

**Comment by viceice** [comment] 2023-01-05 13:33
@HonkingGoose It seemds it can't search for `:` 😕 You can open a new issue you think we should fix that somehow

**Comment by TWiStErRob** [comment] 2023-01-05 13:35
Thanks for revisiting, indeed it's way better now.

**Comment by TWiStErRob** [comment] 2023-01-05 13:39
@HonkingGoose please open another issue for search, I can confirm that search experience is pretty bad for any presets, even when trying to search just for the thing after the `:`. I think tokenization setup is messed up (if it's configurable)
